services:

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5000:5000"
    environment:
      - API_GATEWAY_URL=http://api-gateway:8000
    depends_on:
      - api-gateway

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth-service
    # Aquí puedes agregar los otros servicios base

  # Microservicio de Autenticación
  auth-service:
    build: ./services/authentication
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mongodb://auth-db:27017/auth_db
    depends_on:
      - auth-db

  # Base de datos para el servicio de autenticación
  auth-db:
    image: mongo:latest
    container_name: auth-db
    ports:
      - "27017:27017"
    volumes:
      - auth_data:/data/db

  # --- Plantillas de Microservicios ---
  # TODO: Copiar y modificar "service1" para cada servicio según el tema seleccionado
  
  # Microservicio de Nombre_del_microservicio
  service1-service:
     build: ./services/service1 
     container_name: service1-service
     ports:
       - "8002:8002"
     environment:
       - DATABASE_URL=postgresql://user:password@service1-db:5432/service1_db
     depends_on:
       - service1-db

  # Base de datos para el servicio1
  service1-db:
     image: postgres:latest
     container_name: service1-db
     environment:
       - POSTGRES_USER=user
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=service1_db
     ports:
       - "5432:5432"
     volumes:
       - service1_data:/var/lib/postgresql/data

volumes:
  auth_data:
  service1_data:
  service2_data:
  service3_data:
